authors:
  anastasiia:
    name: Anastasiia But
    description: Architecture, curation, AI/ML pipeline
    avatar: https://avatars.githubusercontent.com/u/92753226
    url: https://www.linkedin.com/in/happyinhappy/
  anastasiya:
    name: Anastasiya Ilukhina
    description: Content, quality review
    avatar: https://avatars.githubusercontent.com/u/165185905?v=4
    url: https://www.linkedin.com/in/anastasiya-ilukhina-09646a289/
