"""
MkDocs hook: auto-count articles per domain at build time.
Generates docs/javascripts/stats.js with window.KS_STATS.
All hardcoded article counts on the site read from this single source.
"""

import os
import json
from pathlib import Path

# Domain folder -> display name + group (for graph coloring)
DOMAIN_META = {
    "data-science":     {"name": "Data Science",      "group": "data"},
    "python":           {"name": "Python",             "group": "code"},
    "web-frontend":     {"name": "Web Frontend",       "group": "code"},
    "devops":           {"name": "DevOps",             "group": "infra"},
    "architecture":     {"name": "Architecture",       "group": "design"},
    "data-engineering":  {"name": "Data Engineering",   "group": "data"},
    "kafka":            {"name": "Kafka",              "group": "infra"},
    "sql-databases":    {"name": "SQL & Databases",    "group": "data"},
    "linux-cli":        {"name": "Linux CLI",          "group": "infra"},
    "llm-agents":       {"name": "LLM & Agents",      "group": "ai"},
    "java-spring":      {"name": "Java & Spring",      "group": "code"},
    "bi-analytics":     {"name": "BI & Analytics",     "group": "data"},
    "algorithms":       {"name": "Algorithms",         "group": "design"},
    "security":         {"name": "Security",           "group": "infra"},
    "seo-marketing":    {"name": "SEO & Marketing",    "group": "other"},
    "testing-qa":       {"name": "Testing & QA",       "group": "design"},
    "rust":             {"name": "Rust",               "group": "code"},
    "php":              {"name": "PHP",                "group": "code"},
    "nodejs":           {"name": "Node.js",            "group": "code"},
    "ios-mobile":       {"name": "iOS & Mobile",       "group": "code"},
    "image-generation": {"name": "Image Generation",   "group": "ai"},
    "cpp":              {"name": "C++",                 "group": "code"},
    "writing":          {"name": "Natural Language & Writing",            "group": "other"},
    "llm-memory":       {"name": "LLM Memory",        "group": "ai"},
    "audio-voice":      {"name": "Voice & Audio",       "group": "ai"},
    "go":               {"name": "Go",                 "group": "code"},
}


def count_articles(docs_dir: Path) -> dict:
    """Count .md articles per domain folder, excluding index.md and special files."""
    domains = {}
    total = 0

    for folder, meta in DOMAIN_META.items():
        domain_path = docs_dir / folder
        if not domain_path.is_dir():
            continue

        count = 0
        for f in domain_path.rglob("*.md"):
            # Skip index files and hidden files
            if f.name == "index.md" or f.name.startswith("."):
                continue
            count += 1

        if count > 0:
            domains[folder] = {
                "name": meta["name"],
                "group": meta["group"],
                "articles": count,
            }
            total += count

    return {
        "total_articles": total,
        "total_domains": len(domains),
        "domains": domains,
    }


def on_pre_build(config, **kwargs):
    """Generate stats.js before MkDocs builds the site."""
    docs_dir = Path(config["docs_dir"])
    stats = count_articles(docs_dir)

    # Build JS with stats
    js_content = f"// Auto-generated by hooks/stats.py - DO NOT EDIT\n"
    js_content += f"// Updated at build time. Single source of truth for all stats.\n"
    js_content += f"window.KS_STATS = {json.dumps(stats, indent=2)};\n"

    # Write to docs/javascripts/stats.js
    out_path = docs_dir / "javascripts" / "stats.js"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(js_content, encoding="utf-8")

    print(f"[stats] {stats['total_articles']} articles across {stats['total_domains']} domains")
